### ISSUE TITLE
代码复现结果问题

### ISSUE THREAD

**Issue by jiaweidoris** [thecharm/Mega#19]
请问论文里代码结果随机种子的设置是多少呀？目前无法复现出论文的结果？其他设置与github描述设置的一致，但是设置不同的随机种子结果差异特别大，请问论文中的结果设置的随机种子是多少呀？

**Comment by panjincan** [comment]
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    framework.train_model('micro_f1')
  File "/root/workspace/Mega-main/opennre/framework/sentence_re.py", line 133, in train_model
    logits = self.parallel_model(*args)
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/workspace/Mega-main/opennre/model/softmax_nn.py", line 46, in forward
    rep = self.sentence_encoder(*args)  # (B, H)
  File "/opt/conda/envs/mega/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/workspace/Mega-main/opennre/encoder/bert_encoder.py", line 164, in forward
    pic = pic.view(-1, 10, self.pic_feat)
RuntimeError: shape '[-1, 10, 4096]' is invalid for input of size 471040

请问这个问题怎么解决呀？
