### ISSUE TITLE
数据集图片打不开的问题

### ISSUE THREAD

**Issue by willing2020** [thecharm/Mega#4]
您好，我下载了数据集，但是图片无法查看，请问需要用什么软件打开图片。

**Comment by thecharm** [comment]
如果图片打不开，你可以通过这个链接下载图片： https://drive.google.com/file/d/1FYiJFtRayWY32nRH0rdycYzIdDcMmDFR/view?usp=sharing

**Comment by willing2020** [comment]
谢谢

**Comment by yangzi0210** [comment]
> 如果图片打不开，你可以通过这个链接下载图片： https://drive.google.com/file/d/1FYiJFtRayWY32nRH0rdycYzIdDcMmDFR/view?usp=sharing

请问这个地址打不开 有没有国内网盘的下载地址 谢谢

**Comment by Kanthon1209** [comment]
因为项目中的那些文件不是图片(虽然后缀名是jpg, 我也不明白为什么 要这么做), 你用文本模式打开就能看到其中的内容
![image](https://github.com/user-attachments/assets/5ba6b0f1-7cb6-4a66-8546-447a4a04a9af)

**Comment by CodeBricks01** [comment]
> 因为项目中的那些文件不是图片(虽然后缀名是jpg, 我也不明白为什么 要这么做), 你用文本模式打开就能看到其中的内容 ![图像](https://private-user-images.githubusercontent.com/78205004/375650677-5ba6b0f1-7cb6-4a66-8546-447a4a04a9af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTQzNjYsIm5iZiI6MTcyODgxNDA2NiwicGF0aCI6Ii83ODIwNTAwNC8zNzU2NTA2NzctNWJhNmIwZjEtN2NiNi00YTY2LTg1NDYtNDQ3YTRhMDRhOWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEwMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzI5MDc5YjExZDAyODE0NWE1NDUzZmVkZWFjNmI4Yjg0NTRhYTNiMDc0NmIyNGFmYzBlNGIxODRhNzE1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZmSrBw2zcXIz5Vn0lswOGRkrbX9oXco4VHO1JWv0TZI)

我想问一下你的imgSG是不是mnre_img为啥我的就是图片，你的是这个，你这个数据是如何获得的，可以告诉我吗，感谢!!!!!

**Comment by Kanthon1209** [comment]
> > 因为项目中的那些文件不是图片(虽然后缀名是jpg, 我也不明白为什么 要这么做), 你用文本模式打开就能看到其中的内容 ![图像]
> 
> 我想问一下你的imgSG是不是mnre_img为啥我的就是图片，你的是这个，你这个数据是如何获得的，可以告诉我吗，感谢!!!!!

作者在指引文件中是这么说的:

>The MNRE dataset used in our paper can be downloaded [here](https://drive.google.com/file/d/1gD9ipQgDEDRxaVxkKr8T0gFFQgKyPpa7/view?usp=sharing). Unzip and move it to ./benchmark/ours/. If you find images unable to open, you can download the images [here](https://drive.google.com/file/d/1FYiJFtRayWY32nRH0rdycYzIdDcMmDFR/view?usp=sharing).

其中第一个文件是处理过后的图片信息, 实际上并不能以图片方式打开, 也就是我图中那样, 第二文件可能就是你可以打开的图片集

**Comment by CodeBricks01** [comment]
> > > 因为项目中的那些文件不是图片(虽然后缀名是jpg, 我也不明白为什么 要这么做), 你用文本模式打开就能看到其中的内容 ![图像]
> > 
> > 
> > 我想问一下你的imgSG是不是mnre_img为啥我的就是图片，你的是这个，你这个数据是如何获得的，可以告诉我吗，感谢!!!!!
> 
> 作者在指引文件中是这么说的:
> 
> > The MNRE dataset used in our paper can be downloaded [here](https://drive.google.com/file/d/1gD9ipQgDEDRxaVxkKr8T0gFFQgKyPpa7/view?usp=sharing). Unzip and move it to ./benchmark/ours/. If you find images unable to open, you can download the images [here](https://drive.google.com/file/d/1FYiJFtRayWY32nRH0rdycYzIdDcMmDFR/view?usp=sharing).
> 
> 其中第一个文件是处理过后的图片信息, 实际上并不能以图片方式打开, 也就是我图中那样, 第二文件可能就是你可以打开的图片集

非常感谢您的回答！！！！！！，我想请问一下您有没有遇到我下面这个情况，如果有的话如何解决的呢，
![image](https://github.com/user-attachments/assets/b559b28e-b12e-4cec-afdf-89ee52c111d4)
Traceback (most recent call last):
  File "C:\Users\\Desktop\Mega-main\example\train.py", line 133, in <module>
    framework.train_model('micro_f1')
  File "C:\Users\\Desktop\Mega-main\opennre\framework\sentence_re.py", line 133, in train_model
    logits = self.parallel_model(*args)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\\Desktop\Mega-main\opennre\model\softmax_nn.py", line 47, in forward
    rep = self.sentence_encoder(*args)  # (B, H)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\\Desktop\Mega-main\opennre\encoder\bert_encoder.py", line 160, in forward
    print("Hidden shape:", hidden.shape)
AttributeError: 'str' object has no attribute 'shape'

**Comment by CodeBricks01** [comment]
> > > 因为项目中的那些文件不是图片(虽然后缀名是jpg, 我也不明白为什么 要这么做), 你用文本模式打开就能看到其中的内容 ![图像]
> > 
> > 
> > 我想问一下你的imgSG是不是mnre_img为啥我的就是图片，你的是这个，你这个数据是如何获得的，可以告诉我吗，感谢!!!!
> 
> 作者在指引文件中是这么说的:
> 
> > 我们论文中使用的 MNRE 数据集可以[在此处](https://drive.google.com/file/d/1gD9ipQgDEDRxaVxkKr8T0gFFQgKyPpa7/view?usp=sharing)下载。解压并将其移动到 ./benchmark/ours/。如果您发现图像无法打开，您可以[在此处](https://drive.google.com/file/d/1FYiJFtRayWY32nRH0rdycYzIdDcMmDFR/view?usp=sharing)下载图像。
> 
> 其中第一个文件是处理过后的图片信息, 实际上并不能以图片方式打开, 也就是我图中那样, 第二文件可能就是你可以打开的图片集

非常感谢您的回答，我想知道那个图片有用到吗？
